# Generated by Django 5.1 on 2024-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
