# Generated by Django 5.1.2 on 2024-11-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletters',
            new_name='Newsletter',
        ),
    ]
