# Generated by Django 5.1.2 on 2024-11-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_newsletters_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Newsletter',
            name='user',
        ),
    ]
