# Generated by Django 5.1 on 2024-09-26 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(uuid.UUID('d923e79d-e2b0-4d50-aa6d-88da3e2d8ef5'), 'Household Items'), (uuid.UUID('bfd35ca7-e2ed-4d9e-bb92-8b95f25c9d46'), 'Kitchen Items'), (uuid.UUID('4cc0b78e-5310-4bdd-8403-c8dfc6f892e8'), 'Office Supplies'), (uuid.UUID('b0250633-4125-4990-87db-be1e0fe1ec89'), 'Clothing and Accessories'), (uuid.UUID('f5ac1fb5-c3e0-43e0-8e83-8ac51da0d57a'), 'Eco Handmade Products'), (uuid.UUID('a9d835f8-8ea3-49c5-b193-7d8791f9aea4'), 'Eco Personal Products')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
