# Generated by Django 5.1.2 on 2024-11-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricing',
            new_name='Pricin',
        ),
    ]
